controller_list:
  - name: sting_arm_controller
    action_ns: "FollowJointTrajectory"
    type: FollowJointTrajectory
    default: True
    joints:
      - shoulder_lateral
      - sholder_vertical
      - elbow
      - lower_arm_yaw
      - lower_arm_vertical
      - gripper_yaw

  - name: sting_gripper_action
    action_ns: ""
    type: GripperCommand
    default: True
    joints:
      - left_finger_joint